// ============================================================
// DATA WILAYAH INDONESIA - LENGKAP (PROVINSI + KOTA)
// ============================================================

const dataWilayah = {
    // ========== PROVINSI ==========
    provinsi: [
        { id: '11', nama: 'Aceh' },
        { id: '12', nama: 'Sumatera Utara' },
        { id: '13', nama: 'Sumatera Barat' },
        { id: '14', nama: 'Riau' },
        { id: '15', nama: 'Jambi' },
        { id: '16', nama: 'Sumatera Selatan' },
        { id: '17', nama: 'Bengkulu' },
        { id: '18', nama: 'Lampung' },
        { id: '19', nama: 'Kepulauan Bangka Belitung' },
        { id: '21', nama: 'Kepulauan Riau' },
        { id: '31', nama: 'DKI Jakarta' },
        { id: '32', nama: 'Jawa Barat' },
        { id: '33', nama: 'Jawa Tengah' },
        { id: '34', nama: 'DI Yogyakarta' },
        { id: '35', nama: 'Jawa Timur' },
        { id: '36', nama: 'Banten' },
        { id: '51', nama: 'Bali' },
        { id: '52', nama: 'Nusa Tenggara Barat' },
        { id: '53', nama: 'Nusa Tenggara Timur' },
        { id: '61', nama: 'Kalimantan Barat' },
        { id: '62', nama: 'Kalimantan Tengah' },
        { id: '63', nama: 'Kalimantan Selatan' },
        { id: '64', nama: 'Kalimantan Timur' },
        { id: '65', nama: 'Kalimantan Utara' },
        { id: '71', nama: 'Sulawesi Utara' },
        { id: '72', nama: 'Sulawesi Tengah' },
        { id: '73', nama: 'Sulawesi Selatan' },
        { id: '74', nama: 'Sulawesi Tenggara' },
        { id: '75', nama: 'Gorontalo' },
        { id: '76', nama: 'Sulawesi Barat' },
        { id: '81', nama: 'Maluku' },
        { id: '82', nama: 'Maluku Utara' },
        { id: '91', nama: 'Papua Barat' },
        { id: '94', nama: 'Papua' },
        { id: '95', nama: 'Papua Selatan' },
        { id: '96', nama: 'Papua Tengah' },
        { id: '97', nama: 'Papua Pegunungan' },
        { id: '98', nama: 'Papua Barat Daya' }
    ],

    // ========== KOTA/KABUPATEN ==========
    kota: [
        // ===== ACEH (11) =====
        { id: '1101', provinsi_id: '11', nama: 'Simeulue' },
        { id: '1102', provinsi_id: '11', nama: 'Aceh Singkil' },
        { id: '1103', provinsi_id: '11', nama: 'Aceh Selatan' },
        { id: '1104', provinsi_id: '11', nama: 'Aceh Tenggara' },
        { id: '1105', provinsi_id: '11', nama: 'Aceh Timur' },
        { id: '1106', provinsi_id: '11', nama: 'Aceh Tengah' },
        { id: '1107', provinsi_id: '11', nama: 'Aceh Barat' },
        { id: '1108', provinsi_id: '11', nama: 'Aceh Besar' },
        { id: '1109', provinsi_id: '11', nama: 'Pidie' },
        { id: '1110', provinsi_id: '11', nama: 'Bireuen' },
        { id: '1111', provinsi_id: '11', nama: 'Aceh Utara' },
        { id: '1112', provinsi_id: '11', nama: 'Aceh Barat Daya' },
        { id: '1113', provinsi_id: '11', nama: 'Gayo Lues' },
        { id: '1114', provinsi_id: '11', nama: 'Aceh Tamiang' },
        { id: '1115', provinsi_id: '11', nama: 'Nagan Raya' },
        { id: '1116', provinsi_id: '11', nama: 'Aceh Jaya' },
        { id: '1117', provinsi_id: '11', nama: 'Bener Meriah' },
        { id: '1118', provinsi_id: '11', nama: 'Pidie Jaya' },
        { id: '1171', provinsi_id: '11', nama: 'Kota Banda Aceh' },
        { id: '1172', provinsi_id: '11', nama: 'Kota Sabang' },
        { id: '1173', provinsi_id: '11', nama: 'Kota Langsa' },
        { id: '1174', provinsi_id: '11', nama: 'Kota Lhokseumawe' },
        { id: '1175', provinsi_id: '11', nama: 'Kota Subulussalam' },

        // ===== SUMATERA UTARA (12) =====
        { id: '1201', provinsi_id: '12', nama: 'Nias' },
        { id: '1202', provinsi_id: '12', nama: 'Mandailing Natal' },
        { id: '1203', provinsi_id: '12', nama: 'Tapanuli Selatan' },
        { id: '1204', provinsi_id: '12', nama: 'Tapanuli Tengah' },
        { id: '1205', provinsi_id: '12', nama: 'Tapanuli Utara' },
        { id: '1206', provinsi_id: '12', nama: 'Toba Samosir' },
        { id: '1207', provinsi_id: '12', nama: 'Labuhanbatu' },
        { id: '1208', provinsi_id: '12', nama: 'Asahan' },
        { id: '1209', provinsi_id: '12', nama: 'Simalungun' },
        { id: '1210', provinsi_id: '12', nama: 'Dairi' },
        { id: '1211', provinsi_id: '12', nama: 'Karo' },
        { id: '1212', provinsi_id: '12', nama: 'Deli Serdang' },
        { id: '1213', provinsi_id: '12', nama: 'Langkat' },
        { id: '1214', provinsi_id: '12', nama: 'Nias Selatan' },
        { id: '1215', provinsi_id: '12', nama: 'Humbang Hasundutan' },
        { id: '1216', provinsi_id: '12', nama: 'Pakpak Bharat' },
        { id: '1217', provinsi_id: '12', nama: 'Samosir' },
        { id: '1218', provinsi_id: '12', nama: 'Serdang Bedagai' },
        { id: '1219', provinsi_id: '12', nama: 'Batu Bara' },
        { id: '1220', provinsi_id: '12', nama: 'Padang Lawas Utara' },
        { id: '1221', provinsi_id: '12', nama: 'Padang Lawas' },
        { id: '1222', provinsi_id: '12', nama: 'Labuhanbatu Selatan' },
        { id: '1223', provinsi_id: '12', nama: 'Labuhanbatu Utara' },
        { id: '1224', provinsi_id: '12', nama: 'Nias Utara' },
        { id: '1225', provinsi_id: '12', nama: 'Nias Barat' },
        { id: '1271', provinsi_id: '12', nama: 'Kota Sibolga' },
        { id: '1272', provinsi_id: '12', nama: 'Kota Tanjungbalai' },
        { id: '1273', provinsi_id: '12', nama: 'Kota Pematangsiantar' },
        { id: '1274', provinsi_id: '12', nama: 'Kota Tebing Tinggi' },
        { id: '1275', provinsi_id: '12', nama: 'Kota Medan' },
        { id: '1276', provinsi_id: '12', nama: 'Kota Binjai' },
        { id: '1277', provinsi_id: '12', nama: 'Kota Padangsidimpuan' },
        { id: '1278', provinsi_id: '12', nama: 'Kota Gunungsitoli' },

        // ===== SUMATERA BARAT (13) =====
        { id: '1301', provinsi_id: '13', nama: 'Kepulauan Mentawai' },
        { id: '1302', provinsi_id: '13', nama: 'Pesisir Selatan' },
        { id: '1303', provinsi_id: '13', nama: 'Solok' },
        { id: '1304', provinsi_id: '13', nama: 'Sijunjung' },
        { id: '1305', provinsi_id: '13', nama: 'Tanah Datar' },
        { id: '1306', provinsi_id: '13', nama: 'Padang Pariaman' },
        { id: '1307', provinsi_id: '13', nama: 'Agam' },
        { id: '1308', provinsi_id: '13', nama: 'Lima Puluh Kota' },
        { id: '1309', provinsi_id: '13', nama: 'Pasaman' },
        { id: '1310', provinsi_id: '13', nama: 'Solok Selatan' },
        { id: '1311', provinsi_id: '13', nama: 'Dharmasraya' },
        { id: '1312', provinsi_id: '13', nama: 'Pasaman Barat' },
        { id: '1371', provinsi_id: '13', nama: 'Kota Padang' },
        { id: '1372', provinsi_id: '13', nama: 'Kota Solok' },
        { id: '1373', provinsi_id: '13', nama: 'Kota Sawahlunto' },
        { id: '1374', provinsi_id: '13', nama: 'Kota Padang Panjang' },
        { id: '1375', provinsi_id: '13', nama: 'Kota Bukittinggi' },
        { id: '1376', provinsi_id: '13', nama: 'Kota Payakumbuh' },
        { id: '1377', provinsi_id: '13', nama: 'Kota Pariaman' },

        // ===== RIAU (14) =====
        { id: '1401', provinsi_id: '14', nama: 'Kuantan Singingi' },
        { id: '1402', provinsi_id: '14', nama: 'Indragiri Hulu' },
        { id: '1403', provinsi_id: '14', nama: 'Indragiri Hilir' },
        { id: '1404', provinsi_id: '14', nama: 'Pelalawan' },
        { id: '1405', provinsi_id: '14', nama: 'Siak' },
        { id: '1406', provinsi_id: '14', nama: 'Kampar' },
        { id: '1407', provinsi_id: '14', nama: 'Rokan Hulu' },
        { id: '1408', provinsi_id: '14', nama: 'Bengkalis' },
        { id: '1409', provinsi_id: '14', nama: 'Rokan Hilir' },
        { id: '1410', provinsi_id: '14', nama: 'Kepulauan Meranti' },
        { id: '1471', provinsi_id: '14', nama: 'Kota Pekanbaru' },
        { id: '1473', provinsi_id: '14', nama: 'Kota Dumai' },

        // ===== JAMBI (15) =====
        { id: '1501', provinsi_id: '15', nama: 'Kerinci' },
        { id: '1502', provinsi_id: '15', nama: 'Merangin' },
        { id: '1503', provinsi_id: '15', nama: 'Sarolangun' },
        { id: '1504', provinsi_id: '15', nama: 'Batanghari' },
        { id: '1505', provinsi_id: '15', nama: 'Muaro Jambi' },
        { id: '1506', provinsi_id: '15', nama: 'Tanjung Jabung Timur' },
        { id: '1507', provinsi_id: '15', nama: 'Tanjung Jabung Barat' },
        { id: '1508', provinsi_id: '15', nama: 'Tebo' },
        { id: '1509', provinsi_id: '15', nama: 'Bungo' },
        { id: '1571', provinsi_id: '15', nama: 'Kota Jambi' },
        { id: '1572', provinsi_id: '15', nama: 'Kota Sungai Penuh' },

        // ===== SUMATERA SELATAN (16) =====
        { id: '1601', provinsi_id: '16', nama: 'Ogan Komering Ulu' },
        { id: '1602', provinsi_id: '16', nama: 'Ogan Komering Ilir' },
        { id: '1603', provinsi_id: '16', nama: 'Muara Enim' },
        { id: '1604', provinsi_id: '16', nama: 'Lahat' },
        { id: '1605', provinsi_id: '16', nama: 'Musi Rawas' },
        { id: '1606', provinsi_id: '16', nama: 'Musi Banyuasin' },
        { id: '1607', provinsi_id: '16', nama: 'Banyuasin' },
        { id: '1608', provinsi_id: '16', nama: 'Ogan Komering Ulu Selatan' },
        { id: '1609', provinsi_id: '16', nama: 'Ogan Komering Ulu Timur' },
        { id: '1610', provinsi_id: '16', nama: 'Ogan Ilir' },
        { id: '1611', provinsi_id: '16', nama: 'Empat Lawang' },
        { id: '1612', provinsi_id: '16', nama: 'Penukal Abab Lematang Ilir' },
        { id: '1613', provinsi_id: '16', nama: 'Musi Rawas Utara' },
        { id: '1671', provinsi_id: '16', nama: 'Kota Palembang' },
        { id: '1672', provinsi_id: '16', nama: 'Kota Prabumulih' },
        { id: '1673', provinsi_id: '16', nama: 'Kota Pagar Alam' },
        { id: '1674', provinsi_id: '16', nama: 'Kota Lubuklinggau' },

        // ===== BENGKULU (17) =====
        { id: '1701', provinsi_id: '17', nama: 'Bengkulu Selatan' },
        { id: '1702', provinsi_id: '17', nama: 'Rejang Lebong' },
        { id: '1703', provinsi_id: '17', nama: 'Bengkulu Utara' },
        { id: '1704', provinsi_id: '17', nama: 'Kaur' },
        { id: '1705', provinsi_id: '17', nama: 'Seluma' },
        { id: '1706', provinsi_id: '17', nama: 'Muko Muko' },
        { id: '1707', provinsi_id: '17', nama: 'Lebong' },
        { id: '1708', provinsi_id: '17', nama: 'Kepahiang' },
        { id: '1709', provinsi_id: '17', nama: 'Bengkulu Tengah' },
        { id: '1771', provinsi_id: '17', nama: 'Kota Bengkulu' },

        // ===== LAMPUNG (18) =====
        { id: '1801', provinsi_id: '18', nama: 'Lampung Barat' },
        { id: '1802', provinsi_id: '18', nama: 'Tanggamus' },
        { id: '1803', provinsi_id: '18', nama: 'Lampung Selatan' },
        { id: '1804', provinsi_id: '18', nama: 'Lampung Timur' },
        { id: '1805', provinsi_id: '18', nama: 'Lampung Tengah' },
        { id: '1806', provinsi_id: '18', nama: 'Lampung Utara' },
        { id: '1807', provinsi_id: '18', nama: 'Way Kanan' },
        { id: '1808', provinsi_id: '18', nama: 'Tulang Bawang' },
        { id: '1809', provinsi_id: '18', nama: 'Pesawaran' },
        { id: '1810', provinsi_id: '18', nama: 'Pringsewu' },
        { id: '1811', provinsi_id: '18', nama: 'Mesuji' },
        { id: '1812', provinsi_id: '18', nama: 'Tulang Bawang Barat' },
        { id: '1813', provinsi_id: '18', nama: 'Pesisir Barat' },
        { id: '1871', provinsi_id: '18', nama: 'Kota Bandar Lampung' },
        { id: '1872', provinsi_id: '18', nama: 'Kota Metro' },

        // ===== KEPULAUAN BANGKA BELITUNG (19) =====
        { id: '1901', provinsi_id: '19', nama: 'Bangka' },
        { id: '1902', provinsi_id: '19', nama: 'Belitung' },
        { id: '1903', provinsi_id: '19', nama: 'Bangka Barat' },
        { id: '1904', provinsi_id: '19', nama: 'Bangka Tengah' },
        { id: '1905', provinsi_id: '19', nama: 'Bangka Selatan' },
        { id: '1906', provinsi_id: '19', nama: 'Belitung Timur' },
        { id: '1971', provinsi_id: '19', nama: 'Kota Pangkal Pinang' },

        // ===== KEPULAUAN RIAU (21) =====
        { id: '2101', provinsi_id: '21', nama: 'Karimun' },
        { id: '2102', provinsi_id: '21', nama: 'Bintan' },
        { id: '2103', provinsi_id: '21', nama: 'Natuna' },
        { id: '2104', provinsi_id: '21', nama: 'Lingga' },
        { id: '2105', provinsi_id: '21', nama: 'Kepulauan Anambas' },
        { id: '2171', provinsi_id: '21', nama: 'Kota Batam' },
        { id: '2172', provinsi_id: '21', nama: 'Kota Tanjung Pinang' },

        // ===== DKI JAKARTA (31) =====
        { id: '3101', provinsi_id: '31', nama: 'Kepulauan Seribu' },
        { id: '3171', provinsi_id: '31', nama: 'Kota Jakarta Selatan' },
        { id: '3172', provinsi_id: '31', nama: 'Kota Jakarta Timur' },
        { id: '3173', provinsi_id: '31', nama: 'Kota Jakarta Pusat' },
        { id: '3174', provinsi_id: '31', nama: 'Kota Jakarta Barat' },
        { id: '3175', provinsi_id: '31', nama: 'Kota Jakarta Utara' },

        // ===== JAWA BARAT (32) =====
        { id: '3201', provinsi_id: '32', nama: 'Bogor' },
        { id: '3202', provinsi_id: '32', nama: 'Sukabumi' },
        { id: '3203', provinsi_id: '32', nama: 'Cianjur' },
        { id: '3204', provinsi_id: '32', nama: 'Bandung' },
        { id: '3205', provinsi_id: '32', nama: 'Garut' },
        { id: '3206', provinsi_id: '32', nama: 'Tasikmalaya' },
        { id: '3207', provinsi_id: '32', nama: 'Ciamis' },
        { id: '3208', provinsi_id: '32', nama: 'Kuningan' },
        { id: '3209', provinsi_id: '32', nama: 'Cirebon' },
        { id: '3210', provinsi_id: '32', nama: 'Majalengka' },
        { id: '3211', provinsi_id: '32', nama: 'Sumedang' },
        { id: '3212', provinsi_id: '32', nama: 'Indramayu' },
        { id: '3213', provinsi_id: '32', nama: 'Subang' },
        { id: '3214', provinsi_id: '32', nama: 'Purwakarta' },
        { id: '3215', provinsi_id: '32', nama: 'Karawang' },
        { id: '3216', provinsi_id: '32', nama: 'Bekasi' },
        { id: '3217', provinsi_id: '32', nama: 'Bandung Barat' },
        { id: '3218', provinsi_id: '32', nama: 'Pangandaran' },
        { id: '3271', provinsi_id: '32', nama: 'Kota Bogor' },
        { id: '3272', provinsi_id: '32', nama: 'Kota Sukabumi' },
        { id: '3273', provinsi_id: '32', nama: 'Kota Bandung' },
        { id: '3274', provinsi_id: '32', nama: 'Kota Cirebon' },
        { id: '3275', provinsi_id: '32', nama: 'Kota Bekasi' },
        { id: '3276', provinsi_id: '32', nama: 'Kota Depok' },
        { id: '3277', provinsi_id: '32', nama: 'Kota Cimahi' },
        { id: '3278', provinsi_id: '32', nama: 'Kota Tasikmalaya' },
        { id: '3279', provinsi_id: '32', nama: 'Kota Banjar' },

        // ===== JAWA TENGAH (33) =====
        { id: '3301', provinsi_id: '33', nama: 'Cilacap' },
        { id: '3302', provinsi_id: '33', nama: 'Banyumas' },
        { id: '3303', provinsi_id: '33', nama: 'Purbalingga' },
        { id: '3304', provinsi_id: '33', nama: 'Banjarnegara' },
        { id: '3305', provinsi_id: '33', nama: 'Kebumen' },
        { id: '3306', provinsi_id: '33', nama: 'Purworejo' },
        { id: '3307', provinsi_id: '33', nama: 'Wonosobo' },
        { id: '3308', provinsi_id: '33', nama: 'Magelang' },
        { id: '3309', provinsi_id: '33', nama: 'Boyolali' },
        { id: '3310', provinsi_id: '33', nama: 'Klaten' },
        { id: '3311', provinsi_id: '33', nama: 'Sukoharjo' },
        { id: '3312', provinsi_id: '33', nama: 'Wonogiri' },
        { id: '3313', provinsi_id: '33', nama: 'Karanganyar' },
        { id: '3314', provinsi_id: '33', nama: 'Sragen' },
        { id: '3315', provinsi_id: '33', nama: 'Grobogan' },
        { id: '3316', provinsi_id: '33', nama: 'Blora' },
        { id: '3317', provinsi_id: '33', nama: 'Rembang' },
        { id: '3318', provinsi_id: '33', nama: 'Pati' },
        { id: '3319', provinsi_id: '33', nama: 'Kudus' },
        { id: '3320', provinsi_id: '33', nama: 'Jepara' },
        { id: '3321', provinsi_id: '33', nama: 'Demak' },
        { id: '3322', provinsi_id: '33', nama: 'Semarang' },
        { id: '3323', provinsi_id: '33', nama: 'Temanggung' },
        { id: '3324', provinsi_id: '33', nama: 'Kendal' },
        { id: '3325', provinsi_id: '33', nama: 'Batang' },
        { id: '3326', provinsi_id: '33', nama: 'Pekalongan' },
        { id: '3327', provinsi_id: '33', nama: 'Pemalang' },
        { id: '3328', provinsi_id: '33', nama: 'Tegal' },
        { id: '3329', provinsi_id: '33', nama: 'Brebes' },
        { id: '3371', provinsi_id: '33', nama: 'Kota Magelang' },
        { id: '3372', provinsi_id: '33', nama: 'Kota Surakarta' },
        { id: '3373', provinsi_id: '33', nama: 'Kota Salatiga' },
        { id: '3374', provinsi_id: '33', nama: 'Kota Semarang' },
        { id: '3375', provinsi_id: '33', nama: 'Kota Pekalongan' },
        { id: '3376', provinsi_id: '33', nama: 'Kota Tegal' },

        // ===== DI YOGYAKARTA (34) =====
        { id: '3401', provinsi_id: '34', nama: 'Kulon Progo' },
        { id: '3402', provinsi_id: '34', nama: 'Bantul' },
        { id: '3403', provinsi_id: '34', nama: 'Gunung Kidul' },
        { id: '3404', provinsi_id: '34', nama: 'Sleman' },
        { id: '3471', provinsi_id: '34', nama: 'Kota Yogyakarta' },

        // ===== JAWA TIMUR (35) =====
        { id: '3501', provinsi_id: '35', nama: 'Pacitan' },
        { id: '3502', provinsi_id: '35', nama: 'Ponorogo' },
        { id: '3503', provinsi_id: '35', nama: 'Trenggalek' },
        { id: '3504', provinsi_id: '35', nama: 'Tulungagung' },
        { id: '3505', provinsi_id: '35', nama: 'Blitar' },
        { id: '3506', provinsi_id: '35', nama: 'Kediri' },
        { id: '3507', provinsi_id: '35', nama: 'Malang' },
        { id: '3508', provinsi_id: '35', nama: 'Lumajang' },
        { id: '3509', provinsi_id: '35', nama: 'Jember' },
        { id: '3510', provinsi_id: '35', nama: 'Banyuwangi' },
        { id: '3511', provinsi_id: '35', nama: 'Bondowoso' },
        { id: '3512', provinsi_id: '35', nama: 'Situbondo' },
        { id: '3513', provinsi_id: '35', nama: 'Probolinggo' },
        { id: '3514', provinsi_id: '35', nama: 'Pasuruan' },
        { id: '3515', provinsi_id: '35', nama: 'Sidoarjo' },
        { id: '3516', provinsi_id: '35', nama: 'Mojokerto' },
        { id: '3517', provinsi_id: '35', nama: 'Jombang' },
        { id: '3518', provinsi_id: '35', nama: 'Nganjuk' },
        { id: '3519', provinsi_id: '35', nama: 'Madiun' },
        { id: '3520', provinsi_id: '35', nama: 'Magetan' },
        { id: '3521', provinsi_id: '35', nama: 'Ngawi' },
        { id: '3522', provinsi_id: '35', nama: 'Bojonegoro' },
        { id: '3523', provinsi_id: '35', nama: 'Tuban' },
        { id: '3524', provinsi_id: '35', nama: 'Lamongan' },
        { id: '3525', provinsi_id: '35', nama: 'Gresik' },
        { id: '3526', provinsi_id: '35', nama: 'Bangkalan' },
        { id: '3527', provinsi_id: '35', nama: 'Sampang' },
        { id: '3528', provinsi_id: '35', nama: 'Pamekasan' },
        { id: '3529', provinsi_id: '35', nama: 'Sumenep' },
        { id: '3571', provinsi_id: '35', nama: 'Kota Kediri' },
        { id: '3572', provinsi_id: '35', nama: 'Kota Blitar' },
        { id: '3573', provinsi_id: '35', nama: 'Kota Malang' },
        { id: '3574', provinsi_id: '35', nama: 'Kota Probolinggo' },
        { id: '3575', provinsi_id: '35', nama: 'Kota Pasuruan' },
        { id: '3576', provinsi_id: '35', nama: 'Kota Mojokerto' },
        { id: '3577', provinsi_id: '35', nama: 'Kota Madiun' },
        { id: '3578', provinsi_id: '35', nama: 'Kota Surabaya' },
        { id: '3579', provinsi_id: '35', nama: 'Kota Batu' },

        // ===== BANTEN (36) =====
        { id: '3601', provinsi_id: '36', nama: 'Pandeglang' },
        { id: '3602', provinsi_id: '36', nama: 'Lebak' },
        { id: '3603', provinsi_id: '36', nama: 'Tangerang' },
        { id: '3604', provinsi_id: '36', nama: 'Serang' },
        { id: '3671', provinsi_id: '36', nama: 'Kota Tangerang' },
        { id: '3672', provinsi_id: '36', nama: 'Kota Cilegon' },
        { id: '3673', provinsi_id: '36', nama: 'Kota Serang' },
        { id: '3674', provinsi_id: '36', nama: 'Kota Tangerang Selatan' },

        // ===== BALI (51) =====
        { id: '5101', provinsi_id: '51', nama: 'Jembrana' },
        { id: '5102', provinsi_id: '51', nama: 'Tabanan' },
        { id: '5103', provinsi_id: '51', nama: 'Badung' },
        { id: '5104', provinsi_id: '51', nama: 'Gianyar' },
        { id: '5105', provinsi_id: '51', nama: 'Klungkung' },
        { id: '5106', provinsi_id: '51', nama: 'Bangli' },
        { id: '5107', provinsi_id: '51', nama: 'Karangasem' },
        { id: '5108', provinsi_id: '51', nama: 'Buleleng' },
        { id: '5171', provinsi_id: '51', nama: 'Kota Denpasar' },

        // ===== NUSA TENGGARA BARAT (52) =====
        { id: '5201', provinsi_id: '52', nama: 'Lombok Barat' },
        { id: '5202', provinsi_id: '52', nama: 'Lombok Tengah' },
        { id: '5203', provinsi_id: '52', nama: 'Lombok Timur' },
        { id: '5204', provinsi_id: '52', nama: 'Sumbawa' },
        { id: '5205', provinsi_id: '52', nama: 'Dompu' },
        { id: '5206', provinsi_id: '52', nama: 'Bima' },
        { id: '5207', provinsi_id: '52', nama: 'Sumbawa Barat' },
        { id: '5208', provinsi_id: '52', nama: 'Lombok Utara' },
        { id: '5271', provinsi_id: '52', nama: 'Kota Mataram' },
        { id: '5272', provinsi_id: '52', nama: 'Kota Bima' },

        // ===== NUSA TENGGARA TIMUR (53) =====
        { id: '5301', provinsi_id: '53', nama: 'Sumba Barat' },
        { id: '5302', provinsi_id: '53', nama: 'Sumba Timur' },
        { id: '5303', provinsi_id: '53', nama: 'Kupang' },
        { id: '5304', provinsi_id: '53', nama: 'Timor Tengah Selatan' },
        { id: '5305', provinsi_id: '53', nama: 'Timor Tengah Utara' },
        { id: '5306', provinsi_id: '53', nama: 'Belu' },
        { id: '5307', provinsi_id: '53', nama: 'Alor' },
        { id: '5308', provinsi_id: '53', nama: 'Lembata' },
        { id: '5309', provinsi_id: '53', nama: 'Flores Timur' },
        { id: '5310', provinsi_id: '53', nama: 'Sikka' },
        { id: '5311', provinsi_id: '53', nama: 'Ende' },
        { id: '5312', provinsi_id: '53', nama: 'Ngada' },
        { id: '5313', provinsi_id: '53', nama: 'Manggarai' },
        { id: '5314', provinsi_id: '53', nama: 'Rote Ndao' },
        { id: '5315', provinsi_id: '53', nama: 'Manggarai Barat' },
        { id: '5316', provinsi_id: '53', nama: 'Sumba Tengah' },
        { id: '5317', provinsi_id: '53', nama: 'Sumba Barat Daya' },
        { id: '5318', provinsi_id: '53', nama: 'Nagekeo' },
        { id: '5319', provinsi_id: '53', nama: 'Manggarai Timur' },
        { id: '5320', provinsi_id: '53', nama: 'Sabu Raijua' },
        { id: '5321', provinsi_id: '53', nama: 'Malaka' },
        { id: '5371', provinsi_id: '53', nama: 'Kota Kupang' },

        // ===== KALIMANTAN BARAT (61) =====
        { id: '6101', provinsi_id: '61', nama: 'Sambas' },
        { id: '6102', provinsi_id: '61', nama: 'Bengkayang' },
        { id: '6103', provinsi_id: '61', nama: 'Landak' },
        { id: '6104', provinsi_id: '61', nama: 'Mempawah' },
        { id: '6105', provinsi_id: '61', nama: 'Sanggau' },
        { id: '6106', provinsi_id: '61', nama: 'Ketapang' },
        { id: '6107', provinsi_id: '61', nama: 'Sintang' },
        { id: '6108', provinsi_id: '61', nama: 'Kapuas Hulu' },
        { id: '6109', provinsi_id: '61', nama: 'Sekadau' },
        { id: '6110', provinsi_id: '61', nama: 'Melawi' },
        { id: '6111', provinsi_id: '61', nama: 'Kayong Utara' },
        { id: '6112', provinsi_id: '61', nama: 'Kubu Raya' },
        { id: '6171', provinsi_id: '61', nama: 'Kota Pontianak' },
        { id: '6172', provinsi_id: '61', nama: 'Kota Singkawang' },

        // ===== KALIMANTAN TENGAH (62) =====
        { id: '6201', provinsi_id: '62', nama: 'Kotawaringin Barat' },
        { id: '6202', provinsi_id: '62', nama: 'Kotawaringin Timur' },
        { id: '6203', provinsi_id: '62', nama: 'Kapuas' },
        { id: '6204', provinsi_id: '62', nama: 'Barito Selatan' },
        { id: '6205', provinsi_id: '62', nama: 'Barito Utara' },
        { id: '6206', provinsi_id: '62', nama: 'Sukamara' },
        { id: '6207', provinsi_id: '62', nama: 'Lamandau' },
        { id: '6208', provinsi_id: '62', nama: 'Seruyan' },
        { id: '6209', provinsi_id: '62', nama: 'Katingan' },
        { id: '6210', provinsi_id: '62', nama: 'Pulang Pisau' },
        { id: '6211', provinsi_id: '62', nama: 'Gunung Mas' },
        { id: '6212', provinsi_id: '62', nama: 'Barito Timur' },
        { id: '6213', provinsi_id: '62', nama: 'Murung Raya' },
        { id: '6271', provinsi_id: '62', nama: 'Kota Palangka Raya' },

        // ===== KALIMANTAN SELATAN (63) =====
        { id: '6301', provinsi_id: '63', nama: 'Tanah Laut' },
        { id: '6302', provinsi_id: '63', nama: 'Kota Baru' },
        { id: '6303', provinsi_id: '63', nama: 'Banjar' },
        { id: '6304', provinsi_id: '63', nama: 'Barito Kuala' },
        { id: '6305', provinsi_id: '63', nama: 'Tapin' },
        { id: '6306', provinsi_id: '63', nama: 'Hulu Sungai Selatan' },
        { id: '6307', provinsi_id: '63', nama: 'Hulu Sungai Tengah' },
        { id: '6308', provinsi_id: '63', nama: 'Hulu Sungai Utara' },
        { id: '6309', provinsi_id: '63', nama: 'Tabalong' },
        { id: '6310', provinsi_id: '63', nama: 'Tanah Bumbu' },
        { id: '6311', provinsi_id: '63', nama: 'Balangan' },
        { id: '6371', provinsi_id: '63', nama: 'Kota Banjarmasin' },
        { id: '6372', provinsi_id: '63', nama: 'Kota Banjar Baru' },

        // ===== KALIMANTAN TIMUR (64) =====
        { id: '6401', provinsi_id: '64', nama: 'Paser' },
        { id: '6402', provinsi_id: '64', nama: 'Kutai Barat' },
        { id: '6403', provinsi_id: '64', nama: 'Kutai Kartanegara' },
        { id: '6404', provinsi_id: '64', nama: 'Kutai Timur' },
        { id: '6405', provinsi_id: '64', nama: 'Berau' },
        { id: '6407', provinsi_id: '64', nama: 'Penajam Paser Utara' },
        { id: '6471', provinsi_id: '64', nama: 'Kota Balikpapan' },
        { id: '6472', provinsi_id: '64', nama: 'Kota Samarinda' },
        { id: '6474', provinsi_id: '64', nama: 'Kota Bontang' },

        // ===== KALIMANTAN UTARA (65) =====
        { id: '6501', provinsi_id: '65', nama: 'Malinau' },
        { id: '6502', provinsi_id: '65', nama: 'Bulungan' },
        { id: '6503', provinsi_id: '65', nama: 'Tana Tidung' },
        { id: '6504', provinsi_id: '65', nama: 'Nunukan' },
        { id: '6571', provinsi_id: '65', nama: 'Kota Tarakan' },

        // ===== SULAWESI UTARA (71) =====
        { id: '7101', provinsi_id: '71', nama: 'Bolaang Mongondow' },
        { id: '7102', provinsi_id: '71', nama: 'Minahasa' },
        { id: '7103', provinsi_id: '71', nama: 'Kepulauan Sangihe' },
        { id: '7104', provinsi_id: '71', nama: 'Kepulauan Talaud' },
        { id: '7105', provinsi_id: '71', nama: 'Minahasa Selatan' },
        { id: '7106', provinsi_id: '71', nama: 'Minahasa Utara' },
        { id: '7107', provinsi_id: '71', nama: 'Bolaang Mongondow Utara' },
        { id: '7108', provinsi_id: '71', nama: 'Siau Tagulandang Biaro' },
        { id: '7109', provinsi_id: '71', nama: 'Minahasa Tenggara' },
        { id: '7110', provinsi_id: '71', nama: 'Bolaang Mongondow Selatan' },
        { id: '7111', provinsi_id: '71', nama: 'Bolaang Mongondow Timur' },
        { id: '7171', provinsi_id: '71', nama: 'Kota Manado' },
        { id: '7172', provinsi_id: '71', nama: 'Kota Bitung' },
        { id: '7173', provinsi_id: '71', nama: 'Kota Tomohon' },
        { id: '7174', provinsi_id: '71', nama: 'Kota Kotamobagu' },

        // ===== SULAWESI TENGAH (72) =====
        { id: '7201', provinsi_id: '72', nama: 'Banggai' },
        { id: '7202', provinsi_id: '72', nama: 'Poso' },
        { id: '7203', provinsi_id: '72', nama: 'Donggala' },
        { id: '7204', provinsi_id: '72', nama: 'Toli Toli' },
        { id: '7205', provinsi_id: '72', nama: 'Buol' },
        { id: '7206', provinsi_id: '72', nama: 'Morowali' },
        { id: '7207', provinsi_id: '72', nama: 'Banggai Kepulauan' },
        { id: '7208', provinsi_id: '72', nama: 'Parigi Moutong' },
        { id: '7209', provinsi_id: '72', nama: 'Tojo Una Una' },
        { id: '7210', provinsi_id: '72', nama: 'Sigi' },
        { id: '7211', provinsi_id: '72', nama: 'Banggai Laut' },
        { id: '7212', provinsi_id: '72', nama: 'Morowali Utara' },
        { id: '7271', provinsi_id: '72', nama: 'Kota Palu' },

        // ===== SULAWESI SELATAN (73) =====
        { id: '7301', provinsi_id: '73', nama: 'Kepulauan Selayar' },
        { id: '7302', provinsi_id: '73', nama: 'Bulukumba' },
        { id: '7303', provinsi_id: '73', nama: 'Bantaeng' },
        { id: '7304', provinsi_id: '73', nama: 'Jeneponto' },
        { id: '7305', provinsi_id: '73', nama: 'Takalar' },
        { id: '7306', provinsi_id: '73', nama: 'Gowa' },
        { id: '7307', provinsi_id: '73', nama: 'Sinjai' },
        { id: '7308', provinsi_id: '73', nama: 'Bone' },
        { id: '7309', provinsi_id: '73', nama: 'Maros' },
        { id: '7310', provinsi_id: '73', nama: 'Pangkajene Kepulauan' },
        { id: '7311', provinsi_id: '73', nama: 'Barru' },
        { id: '7312', provinsi_id: '73', nama: 'Soppeng' },
        { id: '7313', provinsi_id: '73', nama: 'Wajo' },
        { id: '7314', provinsi_id: '73', nama: 'Sidenreng Rappang' },
        { id: '7315', provinsi_id: '73', nama: 'Pinrang' },
        { id: '7316', provinsi_id: '73', nama: 'Enrekang' },
        { id: '7317', provinsi_id: '73', nama: 'Luwu' },
        { id: '7318', provinsi_id: '73', nama: 'Tana Toraja' },
        { id: '7322', provinsi_id: '73', nama: 'Luwu Utara' },
        { id: '7325', provinsi_id: '73', nama: 'Luwu Timur' },
        { id: '7326', provinsi_id: '73', nama: 'Toraja Utara' },
        { id: '7371', provinsi_id: '73', nama: 'Kota Makassar' },
        { id: '7372', provinsi_id: '73', nama: 'Kota Pare Pare' },
        { id: '7373', provinsi_id: '73', nama: 'Kota Palopo' },

        // ===== SULAWESI TENGGARA (74) =====
        { id: '7401', provinsi_id: '74', nama: 'Buton' },
        { id: '7402', provinsi_id: '74', nama: 'Muna' },
        { id: '7403', provinsi_id: '74', nama: 'Konawe' },
        { id: '7404', provinsi_id: '74', nama: 'Kolaka' },
        { id: '7405', provinsi_id: '74', nama: 'Konawe Selatan' },
        { id: '7406', provinsi_id: '74', nama: 'Bombana' },
        { id: '7407', provinsi_id: '74', nama: 'Wakatobi' },
        { id: '7408', provinsi_id: '74', nama: 'Kolaka Utara' },
        { id: '7409', provinsi_id: '74', nama: 'Buton Utara' },
        { id: '7410', provinsi_id: '74', nama: 'Konawe Utara' },
        { id: '7411', provinsi_id: '74', nama: 'Kolaka Timur' },
        { id: '7412', provinsi_id: '74', nama: 'Konawe Kepulauan' },
        { id: '7413', provinsi_id: '74', nama: 'Muna Barat' },
        { id: '7414', provinsi_id: '74', nama: 'Buton Tengah' },
        { id: '7415', provinsi_id: '74', nama: 'Buton Selatan' },
        { id: '7471', provinsi_id: '74', nama: 'Kota Kendari' },
        { id: '7472', provinsi_id: '74', nama: 'Kota Baubau' },

        // ===== GORONTALO (75) =====
        { id: '7501', provinsi_id: '75', nama: 'Boalemo' },
        { id: '7502', provinsi_id: '75', nama: 'Gorontalo' },
        { id: '7503', provinsi_id: '75', nama: 'Pohuwato' },
        { id: '7504', provinsi_id: '75', nama: 'Bone Bolango' },
        { id: '7505', provinsi_id: '75', nama: 'Gorontalo Utara' },
        { id: '7571', provinsi_id: '75', nama: 'Kota Gorontalo' },

        // ===== SULAWESI BARAT (76) =====
        { id: '7601', provinsi_id: '76', nama: 'Mamuju Utara' },
        { id: '7602', provinsi_id: '76', nama: 'Mamuju' },
        { id: '7603', provinsi_id: '76', nama: 'Mamasa' },
        { id: '7604', provinsi_id: '76', nama: 'Polewali Mandar' },
        { id: '7605', provinsi_id: '76', nama: 'Majene' },
        { id: '7606', provinsi_id: '76', nama: 'Pasangkayu' },

        // ===== MALUKU (81) =====
        { id: '8101', provinsi_id: '81', nama: 'Maluku Tenggara Barat' },
        { id: '8102', provinsi_id: '81', nama: 'Maluku Tenggara' },
        { id: '8103', provinsi_id: '81', nama: 'Maluku Tengah' },
        { id: '8104', provinsi_id: '81', nama: 'Buru' },
        { id: '8105', provinsi_id: '81', nama: 'Kepulauan Aru' },
        { id: '8106', provinsi_id: '81', nama: 'Seram Bagian Barat' },
        { id: '8107', provinsi_id: '81', nama: 'Seram Bagian Timur' },
        { id: '8108', provinsi_id: '81', nama: 'Maluku Barat Daya' },
        { id: '8109', provinsi_id: '81', nama: 'Buru Selatan' },
        { id: '8171', provinsi_id: '81', nama: 'Kota Ambon' },
        { id: '8172', provinsi_id: '81', nama: 'Kota Tual' },

        // ===== MALUKU UTARA (82) =====
        { id: '8201', provinsi_id: '82', nama: 'Halmahera Barat' },
        { id: '8202', provinsi_id: '82', nama: 'Halmahera Tengah' },
        { id: '8203', provinsi_id: '82', nama: 'Halmahera Utara' },
        { id: '8204', provinsi_id: '82', nama: 'Halmahera Selatan' },
        { id: '8205', provinsi_id: '82', nama: 'Kepulauan Sula' },
        { id: '8206', provinsi_id: '82', nama: 'Halmahera Timur' },
        { id: '8207', provinsi_id: '82', nama: 'Pulau Morotai' },
        { id: '8208', provinsi_id: '82', nama: 'Pulau Taliabu' },
        { id: '8271', provinsi_id: '82', nama: 'Kota Ternate' },
        { id: '8272', provinsi_id: '82', nama: 'Kota Tidore Kepulauan' },

        // ===== PAPUA BARAT (91) =====
        { id: '9101', provinsi_id: '91', nama: 'Fakfak' },
        { id: '9102', provinsi_id: '91', nama: 'Kaimana' },
        { id: '9103', provinsi_id: '91', nama: 'Teluk Wondama' },
        { id: '9104', provinsi_id: '91', nama: 'Teluk Bintuni' },
        { id: '9105', provinsi_id: '91', nama: 'Manokwari' },
        { id: '9106', provinsi_id: '91', nama: 'Sorong Selatan' },
        { id: '9107', provinsi_id: '91', nama: 'Sorong' },
        { id: '9108', provinsi_id: '91', nama: 'Raja Ampat' },
        { id: '9109', provinsi_id: '91', nama: 'Tambrauw' },
        { id: '9110', provinsi_id: '91', nama: 'Maybrat' },
        { id: '9111', provinsi_id: '91', nama: 'Manokwari Selatan' },
        { id: '9112', provinsi_id: '91', nama: 'Pegunungan Arfak' },
        { id: '9171', provinsi_id: '91', nama: 'Kota Sorong' },

        // ===== PAPUA (94) =====
        { id: '9401', provinsi_id: '94', nama: 'Jayapura' },
        { id: '9402', provinsi_id: '94', nama: 'Jayawijaya' },
        { id: '9403', provinsi_id: '94', nama: 'Paniai' },
        { id: '9404', provinsi_id: '94', nama: 'Puncak Jaya' },
        { id: '9405', provinsi_id: '94', nama: 'Puncak' },
        { id: '9406', provinsi_id: '94', nama: 'Dogiyai' },
        { id: '9407', provinsi_id: '94', nama: 'Intan Jaya' },
        { id: '9408', provinsi_id: '94', nama: 'Deiyai' },
        { id: '9409', provinsi_id: '94', nama: 'Mamberamo Raya' },
        { id: '9410', provinsi_id: '94', nama: 'Yalimo' },
        { id: '9411', provinsi_id: '94', nama: 'Lanny Jaya' },
        { id: '9412', provinsi_id: '94', nama: 'Mamberamo Tengah' },
        { id: '9413', provinsi_id: '94', nama: 'Nduga' },
        { id: '9414', provinsi_id: '94', nama: 'Tolikara' },
        { id: '9415', provinsi_id: '94', nama: 'Yahukimo' },
        { id: '9416', provinsi_id: '94', nama: 'Pegunungan Bintang' },
        { id: '9417', provinsi_id: '94', nama: 'Keerom' },
        { id: '9471', provinsi_id: '94', nama: 'Kota Jayapura' },

        // ===== PAPUA SELATAN (95) =====
        { id: '9501', provinsi_id: '95', nama: 'Merauke' },
        { id: '9502', provinsi_id: '95', nama: 'Boven Digoel' },
        { id: '9503', provinsi_id: '95', nama: 'Mappi' },
        { id: '9504', provinsi_id: '95', nama: 'Asmat' },

        // ===== PAPUA TENGAH (96) =====
        { id: '9601', provinsi_id: '96', nama: 'Nabire' },
        { id: '9602', provinsi_id: '96', nama: 'Paniai' },
        { id: '9603', provinsi_id: '96', nama: 'Mimika' },
        { id: '9604', provinsi_id: '96', nama: 'Puncak' },
        { id: '9605', provinsi_id: '96', nama: 'Dogiyai' },
        { id: '9606', provinsi_id: '96', nama: 'Intan Jaya' },
        { id: '9607', provinsi_id: '96', nama: 'Deiyai' },

        // ===== PAPUA PEGUNUNGAN (97) =====
        { id: '9701', provinsi_id: '97', nama: 'Jayawijaya' },
        { id: '9702', provinsi_id: '97', nama: 'Pegunungan Bintang' },
        { id: '9703', provinsi_id: '97', nama: 'Yahukimo' },
        { id: '9704', provinsi_id: '97', nama: 'Tolikara' },
        { id: '9705', provinsi_id: '97', nama: 'Mamberamo Tengah' },
        { id: '9706', provinsi_id: '97', nama: 'Yalimo' },
        { id: '9707', provinsi_id: '97', nama: 'Lanny Jaya' },
        { id: '9708', provinsi_id: '97', nama: 'Nduga' },

        // ===== PAPUA BARAT DAYA (98) =====
        { id: '9801', provinsi_id: '98', nama: 'Sorong' },
        { id: '9802', provinsi_id: '98', nama: 'Raja Ampat' },
        { id: '9803', provinsi_id: '98', nama: 'Tambrauw' },
        { id: '9804', provinsi_id: '98', nama: 'Maybrat' },
        { id: '9805', provinsi_id: '98', nama: 'Sorong Selatan' },
        { id: '9871', provinsi_id: '98', nama: 'Kota Sorong' }
    ]
};